-- MySQL Script generated by MySQL Workbench
-- Mon Mar 16 11:28:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sisparter-bioskop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisparter-bioskop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisparter-bioskop` DEFAULT CHARACTER SET utf8 ;
USE `sisparter-bioskop` ;

-- -----------------------------------------------------
-- Table `sisparter-bioskop`.`mst_movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisparter-bioskop`.`mst_movie` ;

CREATE TABLE IF NOT EXISTS `sisparter-bioskop`.`mst_movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `image` LONGBLOB NULL,
  `synopsis` MEDIUMTEXT NULL,
  `cast` MEDIUMTEXT NULL,
  `duration` INT NULL,
  `pg_rate` VARCHAR(10) NULL,
  `start_on_air_date` DATE NULL,
  `end_on_air_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisparter-bioskop`.`movie_date_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisparter-bioskop`.`movie_date_schedule` ;

CREATE TABLE IF NOT EXISTS `sisparter-bioskop`.`movie_date_schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movie_date_schedule_movie_idx` (`movie_id` ASC),
  CONSTRAINT `fk_movie_date_schedule_movie`
    FOREIGN KEY (`movie_id`)
    REFERENCES `sisparter-bioskop`.`mst_movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisparter-bioskop`.`mst_studio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisparter-bioskop`.`mst_studio` ;

CREATE TABLE IF NOT EXISTS `sisparter-bioskop`.`mst_studio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisparter-bioskop`.`movie_time_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisparter-bioskop`.`movie_time_schedule` ;

CREATE TABLE IF NOT EXISTS `sisparter-bioskop`.`movie_time_schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DOUBLE NULL,
  `total_ticket` INT NULL,
  `purchased_ticket` VARCHAR(45) NULL,
  `movie_date_schedule_id` INT NOT NULL,
  `mst_studio_id` INT NOT NULL,
  `time` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movie_time_schedule_movie_date_schedule1_idx` (`movie_date_schedule_id` ASC),
  INDEX `fk_movie_time_schedule_mst_studio1_idx` (`mst_studio_id` ASC),
  CONSTRAINT `fk_movie_time_schedule_movie_date_schedule1`
    FOREIGN KEY (`movie_date_schedule_id`)
    REFERENCES `sisparter-bioskop`.`movie_date_schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_time_schedule_mst_studio1`
    FOREIGN KEY (`mst_studio_id`)
    REFERENCES `sisparter-bioskop`.`mst_studio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisparter-bioskop`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sisparter-bioskop`.`transaction` ;

CREATE TABLE IF NOT EXISTS `sisparter-bioskop`.`transaction` (
  `id` VARCHAR(30) NOT NULL,
  `total_ticket` INT NULL,
  `total_price` DOUBLE NULL,
  `customer_name` VARCHAR(100) NULL,
  `movie_time_schedule_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transaction_movie_time_schedule1_idx` (`movie_time_schedule_id` ASC),
  CONSTRAINT `fk_transaction_movie_time_schedule1`
    FOREIGN KEY (`movie_time_schedule_id`)
    REFERENCES `sisparter-bioskop`.`movie_time_schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
